package com.example.bored_bard;

import android.content.Context;

import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

import com.example.bored_bard.dice_roller.DieRoller;

@RunWith(AndroidJUnit4.class)
public class DieRollerInstrumentedTest {
    @Test
    public void verifyAppContext() {
        // this tests that the app context is correct
        Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
        assertEquals("com.example.bored_bard", appContext.getPackageName());
    }

    @Test
    public void checkRangeD4() {
        // This tests that the number generated by the button push
        // is between 1 and 4 (number of sides on a D4)

    }
}
