package com.example.bored_bard;

import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.action.ViewActions.click;
import static androidx.test.espresso.assertion.ViewAssertions.matches;
import static androidx.test.espresso.matcher.ViewMatchers.withId;
import static androidx.test.espresso.matcher.ViewMatchers.withText;

import android.content.Context;

import androidx.test.platform.app.InstrumentationRegistry;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

import com.example.bored_bard.dice_roller.DieRoller;

@RunWith(AndroidJUnit4.class)
public class DieRollerInstrumentedTest {
    @Test
    public void verifyAppContext() {
        // this tests that the app context is correct
        Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
        assertEquals("com.example.bored_bard", appContext.getPackageName());
    }

    private final Exception d4Range = new Exception("Values not within range");

    @Test
    public void checkRangeD4() throws Exception {
        // This tests that the number generated by the button push
        // is between 1 and 4 (number of sides on a D4)
        onView(withId(R.id.d4)).perform(click());
        try {
            onView(withId(R.id.result_window)).check(matches(withText("1")));
            onView(withId(R.id.result_window)).check(matches(withText("2")));
            onView(withId(R.id.result_window)).check(matches(withText("3")));
            onView(withId(R.id.result_window)).check(matches(withText("4")));
        } catch (Exception e) {
            throw d4Range;
        }
    }
}
